# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
project_structure:
  build: build
  contracts: contracts
  interfaces: interfaces
  reports: reports
  scripts: scripts
  tests: tests

networks:
  default: development
  development:
    gas_limit: max
    gas_price: 0
    reverting_tx_gas_limit: max
    default_contract_owner: true
    max_fee: null
    priority_fee: null
    cmd_settings: null
  live:
    gas_limit: auto
    gas_price: auto
    reverting_tx_gas_limit: false
    default_contract_owner: false

compiler:
  evm_version: null
  solc:
    version: null
    optimizer:
      enabled: true
      runs: 200
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.0"
      - "@openzeppelin-upgradable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.8.0"

console:
  show_colors: true
  color_style: monokai
  auto_suggest: true
  completions: true

hypothesis:
  deadline: null
  max_examples: 50
  report_multiple_bugs: False
  stateful_step_count: 10
  phases:
    explicit: true
    reuse: true
    generate: true
    target: true
    shrink: true
autofetch_sources: true
dev_deployment_artifacts: true
reports:
  exclude_contracts:
    - SafeMath
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.8.0