/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { Transfer, TransferInterface } from "../Transfer";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "from",
        type: "address",
      },
      {
        indexed: true,
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        name: "value",
        type: "uint256",
      },
    ],
    name: "Transfer",
    type: "event",
  },
] as const;

export class Transfer__factory {
  static readonly abi = _abi;
  static createInterface(): TransferInterface {
    return new utils.Interface(_abi) as TransferInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Transfer {
    return new Contract(address, _abi, signerOrProvider) as Transfer;
  }
}
